apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      # completions: 5 (N번 수행)
      # parallelism: 2 (동시에 N개 노드에서 수행)
      containers:
        - name: main
          image: luksa/batch-job
