apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia # ReplicationController name
spec:
  replicas: 3
  selector:
    app: kubia-rc # replicas 숫자를 체크할 때 쓰는 key:value
  template:
    metadata:
      labels:
        app: kubia-rc # selector label과 일치시켜야 함.
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
          ports:
            - containerPort: 8080
